name: telegram_notify
on:
  release:
    types: [published]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: A new build of Kiwi Browser Next (preview version) is available. https://github.com/d3ward/src.next/releases/tag/${{ github.event.release.tag_name }}
